/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "ID8Y96rQx6KaJJqQgw7BiaGQ",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
    }
}).schema({
    "todo": a.model({
        id: a.id().required(),
        content: a.string(),
        created_at: a.string(),
        updated_at: a.string()
    }).identifier([
        "id"
    ]).authorization((allow) => [allow.authenticated()])
});
